openapi: 3.0.0
info:
  title: School API
  version: 1.0.0
  description: >
    School API poskytuje data o školách v ČR, včetně adres, oborů, kapacit a kontaktních údajů. Je vhodné pro mapové aplikace, vyhledávače škol, statistiky a školní projekty.

servers:
  - url: https://rybovka23.sps-prosek.cz/Weby/api_endpoint
    description: Produkční server

paths:
  /info.php:
    $ref: "./paths/info.yaml"
  /items.php:
    $ref: "./paths/items.yaml"
  /item.php:
    $ref: "./paths/item.yaml"
  /search.php:
  $ref: "./paths/search.yaml"
